version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sandboxapp
    container_name: app
    restart: unless-stopped
    volumes:
      - ./:/var/www
  
  webserver:
    build:
      context: .
      dockerfile: Dockerfile_Nginx
    image: nginx
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./config/nginx/:/etc/nginx/conf.d/
    depends_on:
      - app

  db:
    image: mariadb:10.9.2
    container_name: db
    restart: unless-stopped
    environment:
       MYSQL_ROOT_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes: 
      - ./mydatabase:/var/lib/mysql