version: '3.8'

services:
  apache-services:
    container_name: Inventory-System
    image: httpd:latest
    ports:
      - '80:80'
    volumes:
    - ./InventorySystem:/usr/local/apache2/htdocs/

  db:
    image: mariadb:10.9.2
    container_name: db
    restart: on-failure
    environment:
       MYSQL_ROOT_PASSWORD: 123
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
