version: '3'
services:

  nginx:
    image: nginx:latest
    networks: 
      codeigniter_net:
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf

  php:
    build: 
      context: ./Ecommerce
      dockerfile: Dockerfile
    volumes:
      - ./Ecommerce:/public
    depends_on:
      - database
    networks:
      codeigniter_net:

  database:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    networks:
      codeigniter_net:
    ports:
      - 3307:3306
    restart: always
  

networks:
  codeigniter_net: