version: '3'
services:

  nginx:
    image: nginx:latest
    networks: 
      codeigniter_net:
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf

  php:
    build: 
      context: ./Ecommerce
      dockerfile: Dockerfile
    volumes:
      - ./Ecommerce:/public
    depends_on:
      - db
    ports:
      - "9000:9000"
      - "8080:80"
    networks:
      codeigniter_net:

  db:
    image: mariadb:10.3.36
    container_name: db
    restart: on-failure
    environment:
       MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'


networks:
  codeigniter_net: