version: '3.8'

services: 
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./Otakuhaven:/var/www/html/
    networks:
      Otakuproxy:
        ipv4_address: 10.10.0.11
    depends_on:
      - db
    
  webserver:
    image: nginx:1.23.2
    container_name: nginx
    ports:
      -  80:80
    restart: on-failure
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      Otakuproxy:
        ipv4_address: 10.10.0.12
  db:
    image: mariadb:10.9.2
    container_name: db
    restart: unless-stopped
    environment:
       MYSQL_ROOT_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes: 
      - ./otakudatabase:/var/lib/mysql
    networks:
      Otakuproxy:
        ipv4_address: 10.10.0.13

networks:
  Otakuproxy:
    ipam:
      config:
        - subnet: 10.10.0.0/16
