version: '3.8'

services:
  webapp:
    image: httpd:latest 
    container_name: app
    restart: on-failure
    ports:
      - 8080:80
    volumes:
      - ./BlogCoffee:/usr/local/apache2/htdocs/
    networks:
      cProxy:
        ipv4_address: 10.10.0.10
 
      

  nginx:
    image: nginx:1.23.2
    container_name: webserver
    ports: 
      - 80:80
    restart: on-failure
    volumes:
      - ./config:/etc/nginx/conf.d
    networks:
      cProxy:
        ipv4_address: 10.10.0.11

networks: 
  cProxy:
    ipam:
      config:
        - subnet: 10.10.0.0/16

