version: '3.8'

services:

  nginx:
    image: nginx:latest
    container_name: SRMS-nginx
    restart: always
    ports: 
      - "8080:80"
    volumes:
    - ../SRMS:/var/www
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
    

  php-app:
     build: 
      context: ./
      dockerfile: Dockerfile
     volumes:
      - ../SRMS:/var/www

  database:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3307:3306
    restart: always
    env_file:
      - .env
    volumes:
      - ./SRMS/database:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file:
      - .env
    ports:
      - 81:80

    